version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - ./src:/src
#    ports:
#      - 8000:8000
#    command: python3 manage.py runserver 0.0.0.0:8000
    command: gunicorn -w 3 first.wsgi:application -b 0.0.0.0:8000 --reload
#    environment:
#      - POSTGRES_PASSWORD=django_pwd
#      - POSTGRES_USER=django_user
#      - POSTGRES_DB=django_db
    env_file:
      - db_keys.txt
    depends_on:
      - db

  db:
    image: postgres
    container_name: my_db
#    environment:
#      - POSTGRES_PASSWORD=django_pwd
#      - POSTGRES_USER=django_user
#      - POSTGRES_DB=django_db
    env_file:
      - db_keys.txt
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:8000
    depends_on:
      - web
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./src:/src
#  adminer:
#    image: adminer

